# Site settings
title: Stilling the Mind
email: 
description: "The purpose of culture is to help us still our mind."
baseurl: ""
url: "http://controlthemind.github.io"
twitter_username: stillthemind
github_username:  stillthemind

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
