# Site settings
title: Control the mind
email: 
description: "Culture is meant to control the mind."
baseurl: ""
url: "http://controlthemind.github.io"
twitter_username: controlthemind
github_username:  controlthemind

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
